---
- hosts: all
  become: yes
  tasks:
  - name: Update APT package cache
    apt:
      update_cache: yes

  - name: Install build-essential, git, and curl
    apt:
      name: 
        - build-essential
        - git
        - curl

  - name: Install Node.js using n-install
    shell: |
      curl -L https://git.io/n-install | bash
    args:
      creates: /etc/profile.d/n-install.sh

  - name: Install Redis (your chosen database)
    apt:
      name: redis-server
      state: latest
    notify:
    - start redis

  - name: Copy your 'userapi' application files
    copy:
      src: /vagrant/userapi/
      dest: /home/vagrant/userapi/
      recursive: yes

  - name: Install 'userapi' application dependencies
    npm:
      path: "/home/vagrant/userapi/"

  - name: Start your 'userapi' Node.js application
    command: npm start
    args:
      chdir: /home/vagrant/userapi/

  - name: Check if 'userapi' application is running (health check)
    uri:
      url: http://localhost:3000/health
      status_code: 200

  handlers:
  - name: start redis
    service:
      name: redis-server
      state: started
      enabled: yes
