apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  labels:
    app: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi-container
        image: gabrieltrier/userapi:latest
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: userapi-service
spec:
  selector:
    app: userapi
  ports:
    - name: http
      protocol: TCP
      port: 80      
      targetPort: 8080

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: userapi-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        number: 8080
        name: http
        protocol: HTTP
    - hosts:
        - "*"
      port:
        number: 8443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: userapi-routing
spec:
  hosts:
    - "*"
  gateways:
    - userapi-gateway
  http:
    - match:
        - uri:
            prefix: "/userapi"
      route:
        - destination:
            host: userapi-service
            port:
              number: 80