version: '3'
services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
  web:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379  
    
volumes:
  redis_data:

