apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-bootcamp
  labels:
    app: kubernetes-bootcamp
spec:
  replicas: 3  # TO COMPLETE #2: Set the desired number of replicas
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
      - name: kubernetes-bootcamp
        image: jocatalin/kubernetes-bootcamp:v1 # TO COMPLETE #1: Set the desired Docker image
