apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
spec:
  type: NodePort
  selector:
    app: kubernetes-bootcamp  # TO COMPLETE: Set the appropriate label for the selector
  ports:
    - port: 8080  # TO COMPLETE: Set the desired port for the service
      
      
