Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64" 

    config.vm.network "forwarded_port", guest:3000, host:3000
  
    config.vm.synced_folder "./userapi", "/home/vagrant/userapi", type: "rsync"
  
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "setup.yml"
    end
  end