Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64" # You can choose any other Linux distribution
  
    config.vm.network "private_network", type: "dhcp"
  
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
  
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end